///
['Goto', _, _, 18]
['ERA', _, _, 'funcionFibonacci']
['param', constante2, 'number', 0]
['gosub', _, _, 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3, _, 7]
['ERA', _, _, 'funcionFibonacci']
['-', local0, constante1, local4]
['param', local4, 'number', 0]
['gosub', _, _, 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3, _, 7]
['return', 'number', local0, global0]
['Goto', _, _, 17]
['ENDPROC', _, _, _]
['ERA', _, _, 'funcionFibonacci']
['+', global0, local0, local5]
['-', local5, constante2, local6]
['param', local6, 'number', 0]
['gosub', _, _, 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3, _, 7]
['return', 'number', local0, global0]
['Goto', _, _, 17]
['ENDPROC', _, _, _]
['return', 'number', global0, global0]
['ENDPROC', _, _, _]
['print', global0, _, _]

GLOBAL
[0]

CONSTANTE
[0, 1, 2]

GOSUB
[[2, 0, 0, 0, 0, 0, 0]]
[[2, False, False, False, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0]]
[[2, False, False, False, 1, 3, 1], [1, 0, 0, 0, 0, 0, 0]]

ENDPROC
[[2, False, False, False, 1, 0, 0], [1, False, True, True, 0, 0, 0]]
[[2, False, False, False, 1, 3, 1], [1, False, True, True, 0, 0, 0]]
[[2, False, False, False, 1, 3, 1]]


/////
['Goto',_ ,_ , 18]
['ERA',_ ,_ , 'funcionFibonacci']
['param', constante3, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante1, local4]
['param', local4, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante1, local4]
['param', local4, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante1, local4]
['param', local4, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['return', 'number', local0, global0]
['Goto',_ ,_ , 17]
['ENDPROC',_ ,_ ,_ ]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante2, local5]
['param', local5, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['return', 'number', local0, global0]
['Goto',_ ,_ , 17]
['ENDPROC',_ ,_ ,_ ]
['+', global0, global0, local6]
['return', 'number', local6, global0]
['ENDPROC',_ ,_ ,_ ]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante2, local5]
['param', local5, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['return', 'number', local0, global0]
['Goto',_ ,_ , 17]
['ENDPROC',_ ,_ ,_ ]
['+', global0, global0, local6]
['return', 'number', local6, global0]
['ENDPROC',_ ,_ ,_ ]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante2, local5]
['param', local5, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante1, local4]
['param', local4, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['return', 'number', local0, global0]
['Goto',_ ,_ , 17]
['ENDPROC',_ ,_ ,_ ]
['ERA',_ ,_ , 'funcionFibonacci']
['-', local0, constante2, local5]
['param', local5, 'number', 0]
['gosub',_ ,_ , 1]
['equal', local0, constante0, local1]
['equal', local0, constante1, local2]
['or', local1, local2, local3]
['GotoF', local3,_ , 7]
['return', 'number', local0, global0]
['Goto',_ ,_ , 17]
['ENDPROC',_ ,_ ,_ ]
['+', global0, global0, local6]
['return', 'number', local6, global0]
['ENDPROC',_ ,_ ,_ ]
['+', global0, global0, local6]
['return', 'number', local6, global0]
['ENDPROC',_ ,_ ,_ ]
['print', global0,_ ,_ ]